config/routes.rb
BrutalSunshine::Application.routes.draw do

  resources :bags

  match 'scene/move' => 'scenes#move'
  match 'scene/search' => 'scenes#search'
  match 'new_game' => 'users#new_game'

  match 'bleed_out' => 'pages#bleed_out'
  match 'death' => 'pages#death'
  match 'killed' => 'pages#killed'
  match 'revenge' => 'pages#revenge'

  resources :scene_objects

  resources :nections

  resources :scenections

  resources :scenes

  root :to => 'pages#index'
  devise_for :users

  resources :users, :only => [:index, :show]

end

app/models/scene.rb
class Scene < ActiveRecord::Base
  attr_accessible :name, :floor, :left_wall, :right_wall, :beginning, :end

  has_many :nections
  has_many :nected, :through => :nections, :source => :scene
  has_many :inverse_nections, :class_name => "Nections", :foreign_key => "adjacent_id"
  has_many :inverse_nected, :through => :inverse_nections, :source => :scene
  
  has_many :scene_objects

  has_many :user_scene_states
  has_many :user_object_states

  has_attached_file :floor, styles: {
    full: '800x600>',
  }
  has_attached_file :left_wall, styles: {
    full: '800x600>',
  }
  has_attached_file :right_wall, styles: {
    full: '800x600>',
  }

  scope :beginning, where(beginning: true)
  scope :end, where(:end => true)

  default_scope order('name ASC')
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  load_and_authorize_resource
  
  def index
  end

  def show
    @directions
    @north = Nection.where('direction = ? AND scene_id = ?', 'north', @scene.id).first
    @east =  Nection.where('direction = ? AND scene_id = ?', 'east',  @scene.id).first
    @south = Nection.where('direction = ? AND scene_id = ?', 'south', @scene.id).first
    @west =  Nection.where('direction = ? AND scene_id = ?', 'west',  @scene.id).first

    redirect_to "/death" if current_user.beats <= 0
    redirect_to "/revenge" if @scene.end? && current_user.gun?
    redirect_to "/killed" if @scene.end? && !current_user.gun?
  end

  def new
  end

  def create
    if @scene.save
      redirect_to @scene, :notice => "Successfully created scene."
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    if @scene.update_attributes(params[:scene])
      redirect_to @scene, :notice  => "Successfully updated scene."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @scene.destroy
    redirect_to scenes_url, :notice => "Successfully destroyed scene.
"  end

  def move
    @scene = Scene.find params[:scene_id]

    @scene.nections.each do |n|
      if n.direction == params[:direction]
        c = current_user
        c.beats -= 1
        c.save
        redirect_to scene_path(n.adjacent)
      end
    end
  end

  def search
    @scene = Scene.find params[:scene_id]
    uss = current_user.user_scene_states.find_by_scene_id(params[:scene_id])
    
    uss.searchable = false
    uss.save

    cu = current_user
    cu.beats -= 1
    cu.save

    if !SceneObject.find_all_by_scene_id(@scene.id).empty?

      current_user.user_object_states.each do |uos|
        if uos.scene_object && uos.scene_object.obtainable?
          flash[:notice] = "You found THE GUN!"
          u = current_user
          u.gun = true
          u.save
          uos.destroy
        else
          flash[:notice] = "You found nothing"
        end
      end
    end
          

    redirect_to scene_path(@scene.id)
  end
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/views/scenes/_form.html.erb
<%= form_for @scene do |f| %>
  <%= f.error_messages %>
  <div class="field">
  <%= f.label :floor %><br />
  <%= f.file_field :floor %>
  </div>
  <div class="field">
  <%= f.label :left_wall %><br />
  <%= f.file_field :left_wall %>
  </div>
  <div class="field">
  <%= f.label :right_wall %><br />
  <%= f.file_field :right_wall %>
  </div>
  <div class="field">
  <%= f.label :beginning %><br />
  <%= f.check_box :beginning %>
  </div>
  <div class="field">
  <%= f.label :end %><br />
  <%= f.check_box :end %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <%= f.submit %>
<% end %>

app/views/scenes/edit.html.erb
<% title "Edit Scene" %>

<%= render 'form' %>

<%= link_to "Show", @scene %> |
<%= link_to "View All", scenes_path %>

app/views/scenes/index.html.erb
<% title "Scenes" %>

<p class="admin">beginning scene: <%= Scene.beginning.first.name unless Scene.beginning.blank? %></p>
<p class="admin">end scene: <%= Scene.end.first.name unless Scene.end.blank? %></p>

<table class="admin">
  <tr>
    <th>Name</th>
  </tr>
  <% for scene in @scenes %>
    <tr>
      <td><%= scene.name %></td>
      <td><%= link_to "Show", scene %></td>
      <td><%= link_to "Edit", edit_scene_path(scene) %></td>
      <td><%= link_to "Destroy", scene, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>
<p>
<%= link_to "New Scene", new_scene_path, :class => "admin" %>
</p>

app/views/scenes/new.html.erb
<% title "New Scene" %>

<%= render 'form' %>

<p><%= link_to "Back to List", scenes_path %></p>

app/views/scenes/show.html.erb
<% title @scene.name %>
  <div id="scene">
    <div id="wall_l" class="ui"><%= image_tag @scene.left_wall.url(:full) %></div>
    <div id="wall_r" class="ui"><%= image_tag @scene.right_wall.url(:full) %></div>
    <div id="floor" class="ui"><%= image_tag @scene.floor.url(:full) %></div>
  <div id="player" class="ui"></div>
  <% @scene.scene_objects.each do |o| %>
    <%= content_tag :div, 'scene_object_id' => o.id, :class => 'ui' do %>
      <%= image_tag o.image.url(:screen) %>
    <% end %>
  <% end %>
  <div class="directions">
    <div id="north" class="ui"><%= link_to @north.label_or_direction, "/scene/move?direction=#{@north.direction}&scene_id=#{@scene.id}" if @north %></div>
    <div id="east" class="ui"><%= link_to @east.label_or_direction, "/scene/move?direction=#{@east.direction}&scene_id=#{@scene.id}" if @east %></div>
    <div id="south" class="ui"><%= link_to @south.label_or_direction, "/scene/move?direction=#{@south.direction}&scene_id=#{@scene.id}" if @south %></div>
    <div id="west" class="ui"><%= link_to @west.label_or_direction, "/scene/move?direction=#{@west.direction}&scene_id=#{@scene.id}" if @west %></div>
  </div>
  <div class="ui"></div>
  <div id="menu" class="ui">
    <div id="heart"><div id="beats"><%= current_user.beats %></div></div>
  </div>
</div>

<% if !@scene.user_scene_states.find_by_user_id(current_user.id).blank? && current_user.admin? %>
  (<%= @scene.user_scene_states.find_by_user_id(current_user.id).searchable? %>)
<% end %>
<%= link_to "Edit", edit_scene_path(@scene) if can? :edit, @scene %> |
<%= link_to "Destroy", @scene, :confirm => 'Are you sure?', :method => :delete if can? :destroy, @scene %> |
<%= link_to "View All", scenes_path if signed_in? && current_user.admin? %>