config/routes.rb
BrutalSunshine::Application.routes.draw do

  resources :bags

  match 'scene/move' => 'scenes#move'
  match 'scene/search' => 'scenes#search'
  match 'new_game' => 'users#new_game'

  match 'bleed_out' => 'pages#bleed_out'
  match 'death' => 'pages#death'
  match 'killed' => 'pages#killed'
  match 'revenge' => 'pages#revenge'

  resources :scene_objects

  resources :nections

  resources :scenections

  resources :scenes

  root :to => 'pages#index'
  devise_for :users

  resources :users, :only => [:index, :show]

end

app/models/scene_object.rb
class SceneObject < ActiveRecord::Base
  attr_accessible :name, :scene_id, :obtainable, :location, :image

  belongs_to :scene

  has_attached_file :image, styles: {
    screen: '800x600',
    half: '200x200',
    full: '400x400'
  }

  scope :searchables, where(obtainable: false)
  scope :obtainables, where(obtainable: true)
end

app/controllers/scene_objects_controller.rb
class SceneObjectsController < ApplicationController
  load_and_authorize_resource

  def index
  end

  def show
  end

  def new
  end

  def create
    if @scene_object.save
      redirect_to @scene_object, :notice => "Successfully created scene object."
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    if @scene_object.update_attributes(params[:scene_object])
      redirect_to @scene_object, :notice  => "Successfully updated scene object."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @scene_object.destroy
    redirect_to scene_objects_url, :notice => "Successfully destroyed scene object."
  end
end

app/helpers/scene_objects_helper.rb
module SceneObjectsHelper
end

app/views/scene_objects/_form.html.erb
<%= form_for @scene_object do |f| %>
  <%= f.error_messages %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :scene_id %><br />
    <%= f.select :scene_id, Scene.all.collect {|s| [s.name, s.id ]} %>
  </div>
  <div class="field">
    <%= f.label :obtainable %><br />
    <%= f.check_box :obtainable %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.select :location, options_for_select([["north (UR)", "north"], ["south (LL)", "south"], ["east (LR)", "east"], ["west (UL)", "west"]], @scene_object.location) %>
  </div>
  <%= f.submit %>
<% end %>

app/views/scene_objects/edit.html.erb
<% title "Edit Scene Object" %>

<%= render 'form' %>

<%= link_to "Show", @scene_object %> |
<%= link_to "View All", scene_objects_path %>

app/views/scene_objects/index.html.erb
<% title "Scene Objects" %>

<table class="admin">
  <tr>
    <th>Name</th>
    <th>Scene</th>
    <th>Obtainable</th>
    <th>Location</th>
  </tr>
  <% for scene_object in @scene_objects %>
    <tr>
      <td><%= scene_object.name if scene_object.scene %></td>
      <td><%= scene_object.scene.name if scene_object.scene %></td>
      <td><%= scene_object.obtainable %></td>
      <td><%= scene_object.location %></td>
      <td><%= link_to "Show", scene_object %></td>
      <td><%= link_to "Edit", edit_scene_object_path(scene_object) %></td>
      <td><%= link_to "Destroy", scene_object, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Scene Object", new_scene_object_path, :class => "admin" %></p>

app/views/scene_objects/new.html.erb
<% title "New Scene Object" %>

<%= render 'form' %>

<p><%= link_to "Back to List", scene_objects_path %></p>

app/views/scene_objects/show.html.erb
<% title "Scene Object" %>

<p>
  <strong>Name:</strong>
  <%= @scene_object.name %>
</p>
<p>
  <strong>Scene:</strong>
  <%= @scene_object.scene.name if @scene_object.scene %>
</p>
<p>
  <strong>Obtainable:</strong>
  <%= @scene_object.obtainable %>
</p>
<p>
  <strong>Location:</strong>
  <%= @scene_object.location %>
</p>
<p>
  <strong>Scene:</strong>
  <%= @scene_object.scene.name if @scene_object.scene %>
</p>

<%= image_tag @scene_object.image.url(:half) %>

<p>
  <%= link_to "Edit", edit_scene_object_path(@scene_object) %> |
  <%= link_to "Destroy", @scene_object, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", scene_objects_path %>
</p>