config/routes.rb
BrutalSunshine::Application.routes.draw do

  resources :bags

  match 'scene/move' => 'scenes#move'
  match 'scene/search' => 'scenes#search'
  match 'new_game' => 'users#new_game'

  match 'bleed_out' => 'pages#bleed_out'
  match 'death' => 'pages#death'
  match 'killed' => 'pages#killed'
  match 'revenge' => 'pages#revenge'

  resources :scene_objects

  resources :nections

  resources :scenections

  resources :scenes

  root :to => 'pages#index'
  devise_for :users

  resources :users, :only => [:index, :show]

end

app/models/bag.rb
class Bag < ActiveRecord::Base
  attr_accessible :user_id

  belongs_to :user
  has_many :scene_objects
end

app/controllers/bags_controller.rb
class BagsController < ApplicationController
  def index
    @bags = Bag.all
  end

  def show
    @bag = Bag.find(params[:id])
  end

  def new
    @bag = Bag.new
  end

  def create
    @bag = Bag.new(params[:bag])
    if @bag.save
      redirect_to @bag, :notice => "Successfully created bag."
    else
      render :action => 'new'
    end
  end

  def edit
    @bag = Bag.find(params[:id])
  end

  def update
    @bag = Bag.find(params[:id])
    if @bag.update_attributes(params[:bag])
      redirect_to @bag, :notice  => "Successfully updated bag."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @bag = Bag.find(params[:id])
    @bag.destroy
    redirect_to bags_url, :notice => "Successfully destroyed bag."
  end

  def add_item

  end
end

app/helpers/bags_helper.rb
module BagsHelper
end

app/views/bags/_form.html.erb
<%= form_for @bag do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/bags/edit.html.erb
<% title "Edit Bag" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @bag %> |
  <%= link_to "View All", bags_path %>
</p>

app/views/bags/index.html.erb
<% title "Bags" %>

<table>
  <tr>
    <th>User</th>
  </tr>
  <% for bag in @bags %>
    <tr>
      <td><%= bag.user_id %></td>
      <td><%= link_to "Show", bag %></td>
      <td><%= link_to "Edit", edit_bag_path(bag) %></td>
      <td><%= link_to "Destroy", bag, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Bag", new_bag_path %></p>

app/views/bags/new.html.erb
<% title "New Bag" %>

<%= render 'form' %>

<p><%= link_to "Back to List", bags_path %></p>

app/views/bags/show.html.erb
<% title "Bag" %>

<p>
  <strong>User:</strong>
  <%= @bag.user_id %>
</p>

<p>
  <%= link_to "Edit", edit_bag_path(@bag) %> |
  <%= link_to "Destroy", @bag, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", bags_path %>
</p>