config/routes.rb
BrutalSunshine::Application.routes.draw do

  resources :bags

  match 'scene/move' => 'scenes#move'
  match 'scene/search' => 'scenes#search'
  match 'new_game' => 'users#new_game'

  match 'bleed_out' => 'pages#bleed_out'
  match 'death' => 'pages#death'
  match 'killed' => 'pages#killed'
  match 'revenge' => 'pages#revenge'

  resources :scene_objects

  resources :nections

  resources :scenections

  resources :scenes

  root :to => 'pages#index'
  devise_for :users

  resources :users, :only => [:index, :show]

end

app/models/nection.rb
class Nection < ActiveRecord::Base
  attr_accessible :scene_id, :adjacent_id, :direction, :label

  belongs_to :scene
  belongs_to :adjacent, :class_name => "Scene"

  def label_or_direction
    return direction if label.blank?
    return label
  end

  def self.by_scene_name
    joins(:scene).order('name ASC')
  end
end

app/controllers/nections_controller.rb
class NectionsController < ApplicationController
  load_and_authorize_resource
  def index
    @nections = Nection.by_scene_name
  end

  def show
  end

  def new
  end

  def create
    @nection = Nection.new(params[:nection])
    
    if @nection.save
      redirect_to @nection, :notice => "Successfully created nection."
    else
      render :action => 'new'
    end
  end

  def edit
    @nection = Nection.find(params[:id])
  end

  def update
    @nection = Nection.find(params[:id])
    if @nection.update_attributes(params[:nection])
      redirect_to @nection, :notice  => "Successfully updated nection."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @nection = Nection.find(params[:id])
    @nection.destroy
    redirect_to nections_url, :notice => "Successfully destroyed nection."
  end
end

app/helpers/nections_helper.rb
module NectionsHelper
end

app/views/nections/_form.html.erb
<%= form_for @nection do |f| %>
  <%= f.error_messages %>
  <div class="field">
    <%= f.label :scene_id %><br />
    <%= f.select :scene_id, Scene.all.collect {|s| [s.name, s.id ]} %>
  </div>
  <div class="field">
    <%= f.label :direction %><br />
    <%= f.select :direction, options_for_select([["north (UR)", "north"], ["south (LL)", "south"], ["east (LR)", "east"], ["west (UL)", "west"]], @nection.direction) %>
  </div>
  <div class="field">
    <%= f.label :adjacent_id %><br />
    <%= f.select :adjacent_id, Scene.all.collect {|s| [s.name, s.id ]} %>
  </div>
  <div class="field">
    <%= f.label :label %><br />
    <%= f.text_field :label %>
  </div>
  <%= f.submit %>
<% end %>

app/views/nections/edit.html.erb
<% title "Edit Nection" %>

<%= render 'form' %>

<%= link_to "Show", @nection %> |
<%= link_to "View All", nections_path %>

app/views/nections/index.html.erb
<% title "Nections" %>

<table class="admin">
  <tr>
    <th>Scene</th>
    <th>Adjacent</th>
    <th>Direction</th>
    <th>Label</th>
  </tr>
  <% for nection in @nections %>
    <tr>
      <td><%= nection.scene.name if nection.scene %></td>
      <td><%= nection.adjacent.name if nection.adjacent %></td>
      <td><%= nection.direction %></td>
      <td><%= nection.label %></td>
      <td><%= link_to "Show", nection %></td>
      <td><%= link_to "Edit", edit_nection_path(nection) %></td>
      <td><%= link_to "Destroy", nection, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Nection", new_nection_path, :class => "admin" %></p>

app/views/nections/new.html.erb
<% title "New Nection" %>

<%= render 'form' %>

<p><%= link_to "Back to List", nections_path %></p>

app/views/nections/show.html.erb
<% title "Nection" %>

<p>
  <strong>Scene:</strong>
  <%= @nection.scene.name if @nection.scene %>
</p>
<p>
  <strong>Adjacent:</strong>
  <%= @nection.adjacent.name if @nection.adjacent %>
</p>
<p>
  <strong>Direction:</strong>
  <%= @nection.direction %>
</p>
<p>
  <strong>Label:</strong>
  <%= @nection.label %>
</p>

<p>
  <%= link_to "Edit", edit_nection_path(@nection) %> |
  <%= link_to "Destroy", @nection, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", nections_path %>
</p>